function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "oddOReven"};
	this.sidHashMap["oddOReven"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "oddOReven:30"};
	this.sidHashMap["oddOReven:30"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "oddOReven:35"};
	this.sidHashMap["oddOReven:35"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<S3>"] = {sid: "oddOReven:6"};
	this.sidHashMap["oddOReven:6"] = {rtwname: "<S3>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "oddOReven:41"};
	this.sidHashMap["oddOReven:41"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/If"] = {sid: "oddOReven:1"};
	this.sidHashMap["oddOReven:1"] = {rtwname: "<Root>/If"};
	this.rtwnameHashMap["<Root>/If Action Subsystem"] = {sid: "oddOReven:30"};
	this.sidHashMap["oddOReven:30"] = {rtwname: "<Root>/If Action Subsystem"};
	this.rtwnameHashMap["<Root>/If Action Subsystem1"] = {sid: "oddOReven:35"};
	this.sidHashMap["oddOReven:35"] = {rtwname: "<Root>/If Action Subsystem1"};
	this.rtwnameHashMap["<Root>/MATLAB Function"] = {sid: "oddOReven:6"};
	this.sidHashMap["oddOReven:6"] = {rtwname: "<Root>/MATLAB Function"};
	this.rtwnameHashMap["<Root>/Merge"] = {sid: "oddOReven:16"};
	this.sidHashMap["oddOReven:16"] = {rtwname: "<Root>/Merge"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "oddOReven:43"};
	this.sidHashMap["oddOReven:43"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<S1>/Action Port"] = {sid: "oddOReven:32"};
	this.sidHashMap["oddOReven:32"] = {rtwname: "<S1>/Action Port"};
	this.rtwnameHashMap["<S1>/String Constant2"] = {sid: "oddOReven:34"};
	this.sidHashMap["oddOReven:34"] = {rtwname: "<S1>/String Constant2"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "oddOReven:33"};
	this.sidHashMap["oddOReven:33"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S2>/Action Port"] = {sid: "oddOReven:36"};
	this.sidHashMap["oddOReven:36"] = {rtwname: "<S2>/Action Port"};
	this.rtwnameHashMap["<S2>/String Constant1"] = {sid: "oddOReven:28"};
	this.sidHashMap["oddOReven:28"] = {rtwname: "<S2>/String Constant1"};
	this.rtwnameHashMap["<S2>/Out1"] = {sid: "oddOReven:38"};
	this.sidHashMap["oddOReven:38"] = {rtwname: "<S2>/Out1"};
	this.rtwnameHashMap["<S3>:1"] = {sid: "oddOReven:6:1"};
	this.sidHashMap["oddOReven:6:1"] = {rtwname: "<S3>:1"};
	this.rtwnameHashMap["<S3>:1:3"] = {sid: "oddOReven:6:1:3"};
	this.sidHashMap["oddOReven:6:1:3"] = {rtwname: "<S3>:1:3"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
