function RTW_rtwnameSIDMap() {
	this.rtwnameHashMap = new Array();
	this.sidHashMap = new Array();
	this.rtwnameHashMap["<Root>"] = {sid: "calc2"};
	this.sidHashMap["calc2"] = {rtwname: "<Root>"};
	this.rtwnameHashMap["<S1>"] = {sid: "calc2:22"};
	this.sidHashMap["calc2:22"] = {rtwname: "<S1>"};
	this.rtwnameHashMap["<S2>"] = {sid: "calc2:13"};
	this.sidHashMap["calc2:13"] = {rtwname: "<S2>"};
	this.rtwnameHashMap["<Root>/Input"] = {sid: "calc2:16"};
	this.sidHashMap["calc2:16"] = {rtwname: "<Root>/Input"};
	this.rtwnameHashMap["<Root>/Divide"] = {sid: "calc2:14"};
	this.sidHashMap["calc2:14"] = {rtwname: "<Root>/Divide"};
	this.rtwnameHashMap["<Root>/Subsystem"] = {sid: "calc2:22"};
	this.sidHashMap["calc2:22"] = {rtwname: "<Root>/Subsystem"};
	this.rtwnameHashMap["<Root>/Output"] = {sid: "calc2:17"};
	this.sidHashMap["calc2:17"] = {rtwname: "<Root>/Output"};
	this.rtwnameHashMap["<Root>/Output1"] = {sid: "calc2:18"};
	this.sidHashMap["calc2:18"] = {rtwname: "<Root>/Output1"};
	this.rtwnameHashMap["<Root>/Output2"] = {sid: "calc2:19"};
	this.sidHashMap["calc2:19"] = {rtwname: "<Root>/Output2"};
	this.rtwnameHashMap["<Root>/Output3"] = {sid: "calc2:20"};
	this.sidHashMap["calc2:20"] = {rtwname: "<Root>/Output3"};
	this.rtwnameHashMap["<S1>/In1"] = {sid: "calc2:23"};
	this.sidHashMap["calc2:23"] = {rtwname: "<S1>/In1"};
	this.rtwnameHashMap["<S1>/MATLAB Function"] = {sid: "calc2:13"};
	this.sidHashMap["calc2:13"] = {rtwname: "<S1>/MATLAB Function"};
	this.rtwnameHashMap["<S1>/Max"] = {sid: "calc2:5"};
	this.sidHashMap["calc2:5"] = {rtwname: "<S1>/Max"};
	this.rtwnameHashMap["<S1>/Min1"] = {sid: "calc2:4"};
	this.sidHashMap["calc2:4"] = {rtwname: "<S1>/Min1"};
	this.rtwnameHashMap["<S1>/Sum of Elements"] = {sid: "calc2:10"};
	this.sidHashMap["calc2:10"] = {rtwname: "<S1>/Sum of Elements"};
	this.rtwnameHashMap["<S1>/Out1"] = {sid: "calc2:24"};
	this.sidHashMap["calc2:24"] = {rtwname: "<S1>/Out1"};
	this.rtwnameHashMap["<S1>/Out2"] = {sid: "calc2:25"};
	this.sidHashMap["calc2:25"] = {rtwname: "<S1>/Out2"};
	this.rtwnameHashMap["<S1>/Out3"] = {sid: "calc2:26"};
	this.sidHashMap["calc2:26"] = {rtwname: "<S1>/Out3"};
	this.rtwnameHashMap["<S1>/y"] = {sid: "calc2:27"};
	this.sidHashMap["calc2:27"] = {rtwname: "<S1>/y"};
	this.rtwnameHashMap["<S2>:1"] = {sid: "calc2:13:1"};
	this.sidHashMap["calc2:13:1"] = {rtwname: "<S2>:1"};
	this.rtwnameHashMap["<S2>:1:3"] = {sid: "calc2:13:1:3"};
	this.sidHashMap["calc2:13:1:3"] = {rtwname: "<S2>:1:3"};
	this.getSID = function(rtwname) { return this.rtwnameHashMap[rtwname];}
	this.getRtwname = function(sid) { return this.sidHashMap[sid];}
}
RTW_rtwnameSIDMap.instance = new RTW_rtwnameSIDMap();
